# Generated by Django 4.2 on 2023-04-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_product_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
